### ISSUE TITLE
Support --newline ?

### ISSUE THREAD

**Issue by esell** [jD91mZM2/powerline-rs#1]
First off, thanks for writing this! I'm typically a go person but am trying to wade into the rust waters :).

What would the level-of-effort be to add newline support? I think it would be a great feature, especially for those of us with smaller screens.

I'm a rust noobie but I will dig in and see if this is something that is fairly painless to implement, and if so, submit a PR. Experienced rust people might be able to beat me to it though...

**Comment by jD91mZM2** [comment]
I don't really see the point of a newline switch because you can just execute `echo` afterwards. But then again, that's less efficient, so maybe you're right.

> I'm a rust noobie but I will dig in and see if this is something that is fairly painless to implement

Awesome! Tell me if you change your mind and I'll do it :)

**Comment by jD91mZM2** [comment]
Closed by #2!

**Comment by jD91mZM2** [comment]
I was reminded by this issue after looking at #3, and I realized that I should probably ask:
What shell are you on @esell? In both bash/zsh you'd assign the prompt to `PS1`, and because of shell substitution the newline gets lost. So in a way this is only usable in fish, which might not be optimal.

**Comment by esell** [comment]
Hey @jD91mZM2, I am a lowly bash user :)

**Comment by jD91mZM2** [comment]
@esell And you're using --newline? Woah, how does that work? Could you please post your prompt initialization script? :)

**Comment by esell** [comment]
This is what I'm using in my `.bash_profile`

```
prompt() {
    PS1="$(powerline-rs2 --newline --shell bash $?)"
}
PROMPT_COMMAND=prompt
```

The `powerline-rs2` is just a reference to my local copy that had these changes before they were merged in :)

**Comment by jD91mZM2** [comment]
Oh, guess I was mistaken about `--newline` not working inside a subshell :stuck_out_tongue:
