### ISSUE TITLE
Compilation issue, release should probably be updated

### ISSUE THREAD

**Issue by sianhulo** [jD91mZM2/powerline-rs#10]
Ok, so I tried to install this from aur which relies on releases, but it failed with an openssl related error, I saw that it tried to build openssl and that the version used was kinda old (0.9x). Snooping round I found that the info related to this was on Cargo.lock, so I compared against master version and saw that it had a bit newer openssl version. After replacing Cargo.lock powerline-rs compiled succesfully. So I think release should be updated, if only just to update Cargo.lock.

**Comment by jD91mZM2** [comment]
Ah yes, rust openssl < 0.10 have issues with the system's 1.1.0 version. I'll bump all the dependencies this afternoon!

**Comment by sianhulo** [comment]
Thank you very much!

**Comment by jD91mZM2** [comment]
Sorry for the delay, life got in the way. Released as version 0.1.9! The AUR package is unfortunately no longer maintained, so you will need to either `cargo install powerline-rs`, or adopt the AUR package yourself if you want to :)
