### ISSUE TITLE
"jobs" segment is shown even if amount of jobs equals 0

### ISSUE THREAD

**Issue by DIzFer** [jD91mZM2/powerline-rs#3]
IMO it would be less confusing if it didn't show at all if there are no background jobs, right? I tried to hack it in, and I realised since the number is filled in by the shell, it's technically impossible. You can see my hack in https://github.com/DIzFer/powerline-rs/commit/1f57e1e5cc91473047d38a3a24a0d6492b05de5f. 

However, I hate it for two reasons: 
  1. It doesn't stop displaying the segment, it's only shown empty.
  2. It has to call three builtins (test, jobs and echo) and an external binary (wc). That's probably much more unneeded slowness, as fast as they might be.

It looks _slightly_ less bad if I put the jobs segment after the root segment, therefore working as a separator, which works around issue 1. But 2, I don't know enough Rust OR shell to fix.

I don't know. I just find the constant 0 distracting, my brain forces me to read it each time my eyes move around the powerline :(

What do you think? Is it worth investing any more time in hiding it better? Should I just discard this commit? Or would a better solution be the implementation of the right-side prompt so that "status" segments can be shown there without making a mess?

**Comment by jD91mZM2** [comment]
I'm not sure - but could the new "ps" segment be what you're looking for? Not technically the same, but might be similar enough for your needs.

**Comment by DIzFer** [comment]
Possibly? If I'm reading the code right, it reads all processes, then counts the ones running in the current TTY? In testing it does work as I'd expect the jobs segment to.

What's the difference then? Under what circumstances would one segment display a different result to the other?

**Comment by jD91mZM2** [comment]
Yup, you saw. Another example is when using nested shells - which was why I made "ps" at first.

**Comment by jD91mZM2** [comment]
Okay so I got a working implementation that's better on zsh because apparently zsh prompts are really powerful :)

Problem is that because powerline has no idea whether or not this segment will show, it transitions into a segment that it then ends up not rendering.

![image](https://user-images.githubusercontent.com/12830969/39967520-ee9849be-56bc-11e8-9aa4-cd6220822d94.png)

@DIzFer

**Comment by DIzFer** [comment]
Nice! How did that work? It's another step forward from what I managed.

I also saw that nix-shell correctly increases the number in ps. Useful! It'll do until a proper nix-shell segment is implemented ;)

**Comment by jD91mZM2** [comment]
@DIzFer So basically in ZSH I just wrapped the whole segment inside `%(1j.` and `.)`. That's zsh speech for `"if jobs >= 1 { "<segment here>" } else { "" }"`. This would cause an error if the segment includes a dot, but luckily that's impossible :relieved:. Any suggestions about how to solve the transition issue?

**Comment by jD91mZM2** [comment]
I could disable transitioning on certain tiles... Sounds like the most sane approach looks really ugly in practice.

![image](https://user-images.githubusercontent.com/12830969/39967828-ec501d98-56c2-11e8-92ca-fae336c8cf91.png)

**Comment by jD91mZM2** [comment]
"Fixed" with 0f13e9114775055449bc30c4092d975c482fcd7a. Please let me know if I should've chosen a better approach :)

**Comment by DIzFer** [comment]
I saw your replies after typing most of this, sorry if it's now partially redundant :'D

Hmmm. So the problem here is that the actual number doesn't "exist" until the shell parses: Rust only knows about %j. Therefore, we need a way to either talk to the shell (which I don't know about), or to quickly count child processes... Which you've already got in the ps segment :)

Now, if I was hacking about for myself, I would guard the jobs segment behind an `if ps.number_to_display() > 0`. But That would make that particular segment weird implementation-wise I think.

BUT I can think of more segments that would only display if ps > 0 (anything involving showing info about a subshell: nix-shell, virtualenv). So, I think generalising part of the ps segment to a condition which segments need to check on before actually running would both allow powerline to hide segments, and lighten the load when said segments are unnecessary.

Also, maybe adding an optional condition check into segments might be in order: new segment ideas might crop up that need X = true before being useful. I went to check on the git segment, which does its own discovery... That looks like a good candidate to implement in this way:
  - The git segment would provide a "pwd_is_git_repo" condition, and a "git" segment.
  - powerline checks is_git_repo before executing anything from the git segment.
  - This opens the door to further modularising gitstage, and each bit of info git displays. And I can then easily add a segment that displays, say, the current commit message (overkill, but just an example) without modifying the other segments.

If this providing of conditions is implemented, the ps segment could implement the current_shell_has_subprocesses condition, on which the ps and jobs segments, as well as the hypothetical nix-shell and virtualenv segments would 

In my scenario, I _think_ a `continue` would happen earlier (only slightly after checking which modules we need, at the same time Shell::bare is found and noop'd) , and therefore the issue with the transitions is moot (since the call to `segments.push()` never happens).

Since this actually feels overengineered, I'll try to implement it and check how much slower it is. I actually want to try and take the opportunity to learn. Expect to hear more about me in about a week or two :)

I also might be a mess at explaining stuff...

**Comment by jD91mZM2** [comment]
Checking `ps` is an awesome idea and I'm ashamed I didn't think of it first :stuck_out_tongue:.
Only potential issue I'm seeing is that it could be weird inside nested shells, but then again I could make that just fallback to my existing transition disable mechanism thing.

What do you mean allowing other segments to be guarded by `ps`? Something like `powerline-rs --modules "cwd,root:ps"` where `root:ps` means "this depends on ps"? Why would anybody ever use that for anything other than jobs? I feel like I'm misunderstanding here.

Again, I might have misunderstood, but I got the impression that you're under the impression that `continue` happens after pushing on `Shell::Bare`. This luckily isn't true, because Rust evaluates the value of the function before actually calling it :)

Anyway, I like your motivation :)
Good luck!
