### ISSUE TITLE
powerline-rs --shell bare --modules host results in the text error.

### ISSUE THREAD

**Issue by michaelmrose** [jD91mZM2/powerline-rs#5]
OS is manjaro current package is from the aur and powerline-rs --version is 0.1.6 shell is fish and hostname is michael-pc

**Comment by michaelmrose** [comment]
This is because it relies on having $HOSTNAME set is it incorrect not to have this set?

**Comment by jD91mZM2** [comment]
That's right, although I really should be relying on something else.

**Comment by jD91mZM2** [comment]
Fixed in 4dda745af8d8ef49f26ac2941b96dc4e88e88308 :)

**Comment by jD91mZM2** [comment]
Did the same thing for usernames and pushed update 0.1.8 :)
